version: '3'
services:
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: root
  #   ports:
  #     - 8081:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   volumes:
  #     - ~/jenkins:/var/jenkins_home
  #     - /usr/bin/docker:/usr/bin/docker
  #     - /usr/local/bin/docker:/usr/local/bin/docker  
  mongodb:
    image: mongo
    container_name: mongo
    ports:
     - 27017-27019:27017-27019
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=password
     - MONGO_INITDB_DATABASE=my-db
     - MONGO_NON_ROOT_USERNAME=admin
     - MONGO_NON_ROOT_PASSWORD=password
    volumes:
        # Add the db-init.js file to the Mongo DB container
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro

  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
     #- ME_CONFIG_MONGODB_AUTH_DATABASE="my-db"
     #- ME_CONFIG_MONGODB_AUTH_USERNAME=admin
     #- ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    restart: unless-stopped
